### ISSUE TITLE
pyproj issue in v08

### ISSUE THREAD

**Issue by tatawang** [CMASCenter/CARS#1]
Hi, Rizzi, I am testing the CARS v08, and get this issue:
   
Calculating the surrograte based on the link shapefile ...
Traceback (most recent call last):
  File "CARS_rev_08_script.py", line 573, in <module>
    main(home_dir, input_dir, output_dir, )
  File "CARS_rev_08_script.py", line 381, in main
   gridfile_name, Radius_Earth, Unit_meters = True ) 
  File "/Users/ctw/PycharmProjects/CARS/CARS_test_Country_KNU/src/CARS_v1_08.py", line 866, in roads_grid_surrogate_inf
   if type(crs) == pyproj.crs.crs.CRS:
AttributeError: module 'pyproj' has no attribute 'crs'

#############
Line 866: if type(crs) == pyproj.crs.crs.CRS:    <= this line is not in v07
 
What version of geopandas are you using??

**Comment by tatawang** [comment]
After I applied the "conda-forge",  (>>conda config --add channels conda-forge), in terminal, I successfully upgrade the geopandas, pyproj and other packages to the latest version. Now I can run CARS v08.
